# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      APPLICATION_SECURITY_JWT_SECRET_KEY: aVeryLongAndSecureRandomSecretKeyForYourJWTTokenGenerationWhichMustBeAtLeast256Bits # Keep in .env for production
      APPLICATION_SECURITY_JWT_EXPIRATION: 3600000
    depends_on:
      db:
        condition: service_healthy
volumes:
  postgres_data: